# Generated by Django 4.1 on 2022-08-29 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('date_publier', models.DateTimeField()),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('domaine', models.CharField(choices=[('Sport', 'Sport'), ('Santer', 'Santer'), ('Soutien Scolaire', 'Soutien Scolaire'), ('Aides Sociales', 'Aides Sociales'), ('Entreprenariat', 'Entreprenariat'), ('Informatique', 'Informatique'), ('Animation', 'Animation')], max_length=20)),
                ('lieu', models.CharField(max_length=50)),
                ('nombre_participant', models.CharField(max_length=50)),
                ('photo_mission', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_publier',),
            },
        ),
        migrations.CreateModel(
            name='Participer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_benevole', models.CharField(max_length=150)),
                ('id_mission', models.CharField(max_length=150)),
                ('est_participer', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='association.mission')),
            ],
        ),
    ]
