# Generated by Django 4.1 on 2022-09-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_remove_participer_est_participer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='date_fin',
            field=models.DateTimeField(null=True),
        ),
    ]
